<?php

declare(strict_types=1);

namespace App\Domain\Enum;

enum EventType: string
{
    case DAMAGE_DEALT = 'DAMAGE_DEALT';
    case HEAL_RECEIVED = 'HEAL_RECEIVED';
    case SHIELD_GAINED = 'SHIELD_GAINED';
    case STATUS_APPLIED = 'STATUS_APPLIED';
    case STATUS_DAMAGE_DEALT = 'STATUS_DAMAGE_DEALT';
    case STATUS_HEAL_RECEIVED = 'STATUS_HEAL_RECEIVED';
    case STATUS_SHIELD_GAINED = 'STATUS_SHIELD_GAINED';
    case STATUS_EXPIRED = 'STATUS_EXPIRED';
}
